extends:
  - stylelint-config-standard
  - stylelint-config-property-sort-order-smacss
customSyntax: "postcss-styled-syntax"
rules:
  at-rule-no-unknown: null
  length-zero-no-unit: true
  function-no-unknown: null
  no-duplicate-selectors: null
  annotation-no-unknown: null
  selector-class-pattern: null
