name: New Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
          scope: "@dynamicyield"

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Prepare for app notarization
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.API_KEY_ID }}.p8

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          args: "--mac --config electron/electron-builder.json -p always"
          github_token: ${{ secrets.GH_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: build:react
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
        env:
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
