name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: 'Bump version'
        required: true
        default: patch
        options:
          - patch
          - minor
          - major
      dry_run:
        type: boolean
        description: 'Dry run'
        required: true
        default: false

concurrency:
  group: ${{ github.event.repository.name }}-release
  cancel-in-progress: true

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Git
        id: prepare-git
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: actions/setup-node@v3
        with:
          always-auth: true
          cache: npm
          check-latest: true
          node-version-file: .nvmrc

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-nodemodules-devkitty-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --audit false

      - name: Bumb version
        run: |
          npm version ${{ github.event.inputs.bump }}
          git push --follow-tags
          echo "new_tag=$(git describe --tags --abbrev=0)" >> $NEW_TAG

      - name: Make
        run: |
          chmod +x add-osx-cert.sh && ./add-osx-cert.sh
          npm run make
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Generate changelog
        id: changelog
        uses: mathieudutour/github-tag-action@v6.1
        with:
          # remove v prefix from $NEW_TAG
          custom_tag: ${NEW_TAG:1}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${NEW_TAG}
          name: Release ${NEW_TAG}
          body: ${{ steps.changelog.outputs.changelog }}
          artifacts: 'out/**/*.zip'
