name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: 'Bump version'
        required: true
        default: patch
        options:
          - patch
          - minor
          - major
      dry_run:
        type: boolean
        description: 'Dry run'
        required: true
        default: false

concurrency:
  group: ${{ github.event.repository.name }}-release
  cancel-in-progress: true

env:
  CI: ${{ github.event.inputs.dry_run == false }}

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Git
        id: prepare-git
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add MacOS certs
        run: chmod +x add-osx-cert.sh && ./add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - uses: actions/setup-node@v3
        with:
          always-auth: true
          cache: npm
          check-latest: true
          node-version-file: .nvmrc

      - run: npm ci --audit false

      - name: Make
        run: npm run make
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          default_bump: ${{ github.event.inputs.bump }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        if: ${{ github.event.inputs.dry_run == false }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: 'out/**/*.zip'
